# OPENSPEC:START
# OpenSpec shell completions configuration
fpath=("/Users/thomas-delalande/.zsh/completions" $fpath)
autoload -Uz compinit
compinit
# OPENSPEC:END

# export SSH_AUTH_SOCK=$HOME/.bitwarden-ssh-agent.sock

# fish


export NVM_DIR="$HOME/.config/nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

if command -v zoxide >/dev/null 2>&1; then
  eval "$(zoxide init zsh)"
fi
