unbind-key C-b
set-option -g prefix C-a
bind-key C-a send-prefix

bind -n WheelUpPane if-shell -F -t = "#{mouse_any_flag}" "send-keys -M" "if -Ft= '#{pane_in_mode}' 'send-keys -M' 'select-pane -t=; copy-mode -e; send-keys -M'"  
bind -n WheelDownPane select-pane -t= \; send-keys -M 

unbind n
bind n if-shell "tmux select-window -t code" "" "new-window; rename-window 'code'; send-keys 'vim' Enter"
unbind g
bind g if-shell "tmux select-window -t git" "" "new-window; rename-window 'git'; send-keys 'lazygit' Enter"
unbind s
bind s if-shell "tmux select-window -t sql" "" "new-window; rename-window 'sql'; send-keys 'nvim +DBUI' Enter"
unbind d
bind d if-shell "tmux select-window -t docker" "" "new-window; rename-window 'docker'; send-keys 'lazydocker' Enter"

unbind q
bind q if-shell "tmux select-window -t shell" "" "new-window; rename-window 'shell';"
unbind a
bind a if-shell "tmux select-window -t agent" "" "new-window; rename-window 'agent'; send-keys '~/dev/ai/scripts/start.sh (pwd) codex' Enter"
unbind A
bind A if-shell "tmux select-window -t agent" "" "new-window; rename-window 'agent'; send-keys '~/dev/ai/scripts/start.sh (pwd) copilot' Enter"

unbind w
# Show windows in current session
bind w run-shell 'tmux choose-tree -Nwf"##{==:##{session_name},#{session_name}}"'
bind W run-shell 'tmux choose-tree -w'

unbind k
bind k kill-pane -a -t :
unbind K
bind K kill-window -a -t :

unbind P
bind P choose-tree -s

unbind p
bind-key "p" run-shell "sesh connect \"$(
  sesh list --icons | fzf-tmux -p 55%,60% \
    --no-sort --ansi --border-label ' sesh ' --prompt '⚡  ' \
    --header '  ^a all ^t tmux ^g configs ^x zoxide ^d tmux kill ^f find' \
    --bind 'tab:down,btab:up' \
    --bind 'ctrl-a:change-prompt(⚡  )+reload(sesh list --icons)' \
    --bind 'ctrl-t:change-prompt(🪟  )+reload(sesh list -t --icons)' \
    --bind 'ctrl-g:change-prompt(⚙️  )+reload(sesh list -c --icons)' \
    --bind 'ctrl-x:change-prompt(📁  )+reload(sesh list -z --icons)' \
    --bind 'ctrl-f:change-prompt(🔎  )+reload(fd -H -d 2 -t d -E .Trash . ~)' \
    --bind 'ctrl-d:execute(tmux kill-session -t {2..})+change-prompt(⚡  )+reload(sesh list --icons)' \
)\""

set -g base-index 1
setw -g pane-base-index 1

set -s escape-time 0

set-option -g renumber-windows on
setw -g mouse on

set-option -g repeat-time 1000

bind -r C-h select-window -t :-
bind -r C-l select-window -t :+
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
bind tab last-window 

bind-key r source-file ~/.config/tmux/tmux.conf \; display-message "~/.config/tmux/tmux.conf reloaded"

set-window-option -g mode-keys vi

set -g status-left ""
set -g status-right ""
setw -g status-left ""

setw -g status-left-style fg=colour240,bg=default
setw -g status-style fg=colour240,bg=default

setw -g status-right ""
setw -g status-right-style fg=colour220,bg=default

setw -g window-status-current-format ""
setw -g window-status-current-style fg=colour111,bg=default

setw -g window-status-format ""
setw -g window-status-style fg=colour240,bg=default

set -g pane-border-style fg=colour233,bg=default
set -g pane-active-border-style fg=colour235,bg=colour235

